language: node_js
node_js:
  - "0.10"
  - "0.12"

script:
  - npm test
after_success:
  - npm install -g istanbul
  - npm install coveralls
  - istanbul cover test/servus.test.js --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage